# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04]
        node_version: ['10']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Set env
      run: node version-changer.js
    - name: npm install, build and test (windows-only) 
      env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: contains(matrix.os, 'window')
      run: |
        echo ${LATEST_TAG_DISTANCE}
        npm install
        npm run electron:build:win -- -p always
    - name: npm install, build and test (linux-only) 
      env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: contains(matrix.os, 'ubuntu')  
      run: |
        npm install
        npm run electron:build:linux -- -p always
    - uses: actions/upload-artifact@v2
      with:
        name: task-board-${{ matrix.os }}
        path: |
          dist_electron/task-board*.deb
          dist_electron/task-board*.exe
