# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: ['10']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Set env
      run: |
          GIT_DESCRIBE="$(git describe --tags)"
          IFS='-' read -r -a CHUNKS <<< "$GIT_DESCRIBE"
          TAG=${CHUNKS[0]}
          TAG_DISTANCE=${CHUNKS[1]}
          COMMIT_HASH=${CHUNKS[2]}
          echo $TAG
          echo $TAG_DISTANCE
          echo $COMMIT_HASH
          sed -i "s/\"version\": \".*\"/\"version\": \"$TAG\"/" package.json
          if [ $TAG_DISTANCE -gt 0 ]
          then
            sed -i "s/\"version\": \".*\"/\"version\": \"$TAG\"/" package.json
          else
            sed -i "s/\"version\": \".*\"/\"version\": \"$TAG+$TAG_DISTANCE-$COMMIT_HASH\"/" package.json
          fi
    - name: npm install, build and test
      run: |
        npm install
        npm run electron:build:linux
